Feature/oh2 180 account started
ourherd/ourherd_microservices_backend pull request #7
Opened 2023-10-20 06:45 UTC by jokekerker

2023-10-21 01:11 UTC, ronsandova requested changes
Just a few changes I stopped reviewing it when we chatted

2023-10-24 02:43 UTC, ronsandova requested changes
Please review

2023-10-24 02:43 UTC, ronsandova commented on apps/account/src/account.service.ts
> +  async login(loginAccountDto: LoginAccountDto): Promise<IServiceResponse<any>> {
Please response an interface or type **NO ANY**

2023-10-24 02:43 UTC, ronsandova commented on apps/gateway/src/modules/member/member-profile-gateway.controller.ts
> +  @Roles(Role.ADMIN)
Remove this @Roles decorator

2023-10-24 02:43 UTC, ronsandova commented on apps/gateway/src/modules/member/member-profile-gateway.controller.ts
> +    @Request() req: any
What the req for ?

2023-10-24 02:43 UTC, ronsandova commented on apps/account/src/dto/register.account.dto.ts
>    ADMIN = 'ADMIN'
Please lets maintain 1 role enumerator 

import { ROLES_KEY, Roles } from "../decorator/role.decorator";

2023-10-24 02:43 UTC, ronsandova commented on apps/account/src/dto/register.account.dto.ts
>    // @IsUUID()
Remove comment

2023-10-24 02:43 UTC, ronsandova commented on apps/gateway/src/gateway.module.ts
> +import { CognitoAuthModule } from '@nestjs-cognito/auth';
Did you check the health of the library?

2023-10-24 02:43 UTC, ronsandova commented on apps/gateway/src/modules/account/account-gateway.controller.ts
> +      this.accountClient.send<IServiceResponse<any>, { loginDto: LoginAccountDto}>
Don't return any

2023-10-24 02:54 UTC, ronsandova requested changes

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/account.service.ts
> +    console.log("HASH password",hash);
remove if you wanna log use LOGGER

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/account.service.ts
> +    accountEntity.password_hash = hash
Please refer to save and create instead of set the Entity (repo), use injection

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/account.service.ts
> +    console.log(cognito_user);
remove

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/account.service.ts
> +      // loginAccountDto.password = await bcrypt.hash(loginAccountDto.password, saltOrRounds);
remove

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/account.service.ts
> +      const saltOrRounds = 10;
its been use twice, create a const at the top as a global variable

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/account.service.ts
> +      console.log(loginAccountDto);
remove

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/account.service.ts
> +      console.log(e)
remove

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/aws-cognito.service.ts
> +      UserPoolId: process.env.AWS_COGNITO_USER_POOL_ID,
change this for the env variables not process
Add the 

AWS_COGNITO_USER_POOL_ID
AWS_COGNITO_CLIENT_ID

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/constant/account-patterns.constants.ts
>    CREATE: 'account.create',
register

2023-10-24 02:54 UTC, ronsandova commented on apps/account/src/dto/login.account.dto.ts
> +  @IsString()
Password has a pattern to be validate it

2023-10-24 02:54 UTC, ronsandova commented on apps/gateway/src/modules/account/account-gateway.controller.ts
>          ACCOUNT_MESSAGE_PATTERNS.CREATE,
register instead of create

2023-10-24 04:25 UTC, jokekerker commented on apps/account/src/account.module.ts
> +    RabbitModule.forClientProxy(RabbitServiceName.MEMBER),
if you have time huddle with me about this please.

2023-10-26 00:31 UTC, merged